[2024-04-08T07:48:44.363+0000] {processor.py:161} INFO - Started process (PID=35554) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:48:44.364+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:48:44.364+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.364+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:48:44.371+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:48:44.476+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.475+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:dog_api_pipeline
[2024-04-08T07:48:44.488+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.488+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:dog_api_pipeline
[2024-04-08T07:48:44.498+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.497+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:dog_api_pipeline
[2024-04-08T07:48:44.498+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.498+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:48:44.507+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.507+0000] {dag.py:3069} INFO - Creating ORM DAG for dog_api_pipeline
[2024-04-08T07:48:44.515+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:48:44.515+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:48:44.532+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.172 seconds
[2024-04-08T07:49:15.268+0000] {processor.py:161} INFO - Started process (PID=35817) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:15.269+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:49:15.270+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:15.270+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:15.278+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:15.295+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:15.295+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:49:15.313+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:15.313+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:49:15.332+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.067 seconds
[2024-04-08T07:49:45.874+0000] {processor.py:161} INFO - Started process (PID=36080) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:45.874+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:49:45.875+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:45.875+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:45.882+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:49:45.898+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:45.897+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:49:45.915+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:49:45.915+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:49:45.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.063 seconds
[2024-04-08T07:50:16.370+0000] {processor.py:161} INFO - Started process (PID=36342) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:16.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:50:16.371+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:16.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:16.378+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:16.394+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:16.394+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:50:16.412+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:16.412+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:50:16.431+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.064 seconds
[2024-04-08T07:50:46.680+0000] {processor.py:161} INFO - Started process (PID=36605) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:46.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:50:46.682+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:46.681+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:46.693+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:50:46.717+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:46.717+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:50:46.744+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:50:46.744+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:50:46.766+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.091 seconds
[2024-04-08T07:51:14.756+0000] {processor.py:161} INFO - Started process (PID=36852) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:14.757+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:14.758+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:14.757+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:14.764+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:14.764+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 29, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-04-08T07:51:14.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:14.786+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.033 seconds
[2024-04-08T07:51:17.894+0000] {processor.py:161} INFO - Started process (PID=36873) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:17.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:17.896+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:17.896+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:17.906+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:17.905+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 29, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-04-08T07:51:17.906+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:17.937+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.048 seconds
[2024-04-08T07:51:24.925+0000] {processor.py:161} INFO - Started process (PID=36878) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:24.926+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:24.927+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:24.927+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:24.936+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:24.935+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 29, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-04-08T07:51:24.936+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:24.963+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.041 seconds
[2024-04-08T07:51:35.893+0000] {processor.py:161} INFO - Started process (PID=36974) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:35.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:35.895+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:35.894+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:35.902+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:35.901+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:51:35.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:35.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-04-08T07:51:40.762+0000] {processor.py:161} INFO - Started process (PID=37099) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:40.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:40.770+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:40.769+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:40.788+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:40.787+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:51:40.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:40.819+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.059 seconds
[2024-04-08T07:51:47.230+0000] {processor.py:161} INFO - Started process (PID=37148) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:47.232+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:47.232+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:47.232+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:47.241+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:47.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 25, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:51:47.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:47.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.045 seconds
[2024-04-08T07:51:56.650+0000] {processor.py:161} INFO - Started process (PID=37175) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:56.651+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:51:56.651+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:56.651+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:56.657+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:51:56.657+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:51:56.658+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:51:56.678+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:52:04.277+0000] {processor.py:161} INFO - Started process (PID=37245) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:04.278+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:04.279+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:04.278+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:04.285+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:04.284+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:04.285+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:04.306+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:52:07.530+0000] {processor.py:161} INFO - Started process (PID=37271) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:07.531+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:07.532+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:07.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:07.539+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:07.539+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:07.540+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:07.566+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-04-08T07:52:09.796+0000] {processor.py:161} INFO - Started process (PID=37346) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:09.796+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:09.797+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:09.797+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:09.803+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:09.802+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:09.803+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:09.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.031 seconds
[2024-04-08T07:52:15.856+0000] {processor.py:161} INFO - Started process (PID=37416) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:15.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:15.857+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:15.857+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:15.860+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:15.859+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 12
    requests = requests.get("https://dog.ceo/api/breeds/image/random Fetch!
                                                                          ^
SyntaxError: EOL while scanning string literal
[2024-04-08T07:52:15.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:15.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.028 seconds
[2024-04-08T07:52:19.999+0000] {processor.py:161} INFO - Started process (PID=37437) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:20.000+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:20.001+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:20.000+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:20.006+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:20.006+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 24, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:20.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:20.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:52:35.286+0000] {processor.py:161} INFO - Started process (PID=37533) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:35.287+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:35.295+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:35.294+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:35.303+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:35.302+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 27, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:35.303+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:35.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.050 seconds
[2024-04-08T07:52:38.480+0000] {processor.py:161} INFO - Started process (PID=37553) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:38.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:38.483+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:38.482+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:38.491+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:38.490+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 25, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:38.491+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:38.572+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.097 seconds
[2024-04-08T07:52:44.081+0000] {processor.py:161} INFO - Started process (PID=37688) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:44.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:44.083+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:44.083+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:44.089+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:44.088+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 26, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:52:44.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:44.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-04-08T07:52:57.585+0000] {processor.py:161} INFO - Started process (PID=37734) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:57.595+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:57.596+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:57.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:57.600+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:57.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open()
              ^
SyntaxError: invalid syntax
[2024-04-08T07:52:57.609+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:57.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.073 seconds
[2024-04-08T07:52:58.655+0000] {processor.py:161} INFO - Started process (PID=37739) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:58.656+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:52:58.657+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:58.656+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:58.660+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:52:58.659+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("")
                ^
SyntaxError: invalid syntax
[2024-04-08T07:52:58.660+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:52:58.685+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.034 seconds
[2024-04-08T07:53:01.996+0000] {processor.py:161} INFO - Started process (PID=37764) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:01.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:02.001+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:01.998+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:02.006+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:02.005+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("")
                ^
SyntaxError: invalid syntax
[2024-04-08T07:53:02.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:02.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.048 seconds
[2024-04-08T07:53:07.624+0000] {processor.py:161} INFO - Started process (PID=37821) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:07.625+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:07.626+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:07.626+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:07.629+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:07.628+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow")
                            ^
SyntaxError: invalid syntax
[2024-04-08T07:53:07.630+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:07.655+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-04-08T07:53:09.107+0000] {processor.py:161} INFO - Started process (PID=37841) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:09.108+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:09.109+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:09.108+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:09.111+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:09.111+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/")
                             ^
SyntaxError: invalid syntax
[2024-04-08T07:53:09.112+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:09.140+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.037 seconds
[2024-04-08T07:53:14.300+0000] {processor.py:161} INFO - Started process (PID=37976) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:14.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:14.302+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:14.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:14.305+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:14.304+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags")
                                 ^
SyntaxError: invalid syntax
[2024-04-08T07:53:14.306+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:14.329+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:53:16.316+0000] {processor.py:161} INFO - Started process (PID=37981) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:16.317+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:16.317+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:16.317+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:16.320+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:16.319+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.")
                                      ^
SyntaxError: invalid syntax
[2024-04-08T07:53:16.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:16.346+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.033 seconds
[2024-04-08T07:53:18.398+0000] {processor.py:161} INFO - Started process (PID=38001) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:18.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:18.400+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:18.399+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:18.403+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:18.401+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json,")
                                           ^
SyntaxError: invalid syntax
[2024-04-08T07:53:18.403+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:18.423+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.028 seconds
[2024-04-08T07:53:19.413+0000] {processor.py:161} INFO - Started process (PID=38006) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:19.414+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:19.416+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:19.415+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:19.419+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:19.418+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json, ")
                                            ^
SyntaxError: invalid syntax
[2024-04-08T07:53:19.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:19.448+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-04-08T07:53:21.310+0000] {processor.py:161} INFO - Started process (PID=38017) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:21.311+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:21.312+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:21.312+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:21.315+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:21.314+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json, ")
                                            ^
SyntaxError: invalid syntax
[2024-04-08T07:53:21.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:21.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-04-08T07:53:23.319+0000] {processor.py:161} INFO - Started process (PID=38022) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:23.320+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:23.321+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:23.321+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:23.323+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:23.323+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json, "")
                                             ^
SyntaxError: EOL while scanning string literal
[2024-04-08T07:53:23.324+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:23.344+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.027 seconds
[2024-04-08T07:53:25.345+0000] {processor.py:161} INFO - Started process (PID=38027) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:25.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:25.349+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:25.348+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:25.353+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:25.352+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json, "w")
                                            ^
SyntaxError: invalid syntax
[2024-04-08T07:53:25.353+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:25.380+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.039 seconds
[2024-04-08T07:53:29.660+0000] {processor.py:161} INFO - Started process (PID=38052) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:29.661+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:29.662+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:29.662+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:29.665+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:29.665+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 15
    with open("/opt/airflow/dags.dog.json", "w")
                                               ^
SyntaxError: invalid syntax
[2024-04-08T07:53:29.666+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:29.693+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.036 seconds
[2024-04-08T07:53:33.017+0000] {processor.py:161} INFO - Started process (PID=38077) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:33.018+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:33.020+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:33.019+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:33.023+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:33.022+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 18
    with DAG(
            ^
IndentationError: expected an indented block
[2024-04-08T07:53:33.023+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:33.078+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.065 seconds
[2024-04-08T07:53:34.836+0000] {processor.py:161} INFO - Started process (PID=38127) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:34.836+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:34.837+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:34.837+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:34.839+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:34.839+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 16
    f.
     ^
SyntaxError: invalid syntax
[2024-04-08T07:53:34.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:34.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.027 seconds
[2024-04-08T07:53:44.689+0000] {processor.py:161} INFO - Started process (PID=38284) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:44.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:44.691+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:44.690+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:44.698+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:44.698+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 28, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:53:44.699+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:44.724+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.038 seconds
[2024-04-08T07:53:45.704+0000] {processor.py:161} INFO - Started process (PID=38289) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:45.705+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:45.706+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:45.706+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:45.711+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:45.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 28, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:53:45.712+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:45.734+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:53:46.762+0000] {processor.py:161} INFO - Started process (PID=38294) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:46.763+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:46.764+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:46.764+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:46.773+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:46.772+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 28, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:53:46.773+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:46.816+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.057 seconds
[2024-04-08T07:53:51.900+0000] {processor.py:161} INFO - Started process (PID=38314) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:51.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:53:51.903+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:51.903+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:51.912+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:53:51.911+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 29, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:53:51.912+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:53:51.964+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.071 seconds
[2024-04-08T07:54:00.364+0000] {processor.py:161} INFO - Started process (PID=38345) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:00.365+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:54:00.366+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:00.366+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:00.374+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:00.373+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 29, in <module>
    python_callable=_get_dog_api,
NameError: name '_get_dog_api' is not defined
[2024-04-08T07:54:00.374+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:00.404+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.043 seconds
[2024-04-08T07:54:08.240+0000] {processor.py:161} INFO - Started process (PID=38421) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:08.241+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:54:08.242+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:08.241+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:08.248+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:08.247+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-04-08T07:54:08.248+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:08.270+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.032 seconds
[2024-04-08T07:54:38.513+0000] {processor.py:161} INFO - Started process (PID=38684) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:38.514+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:54:38.514+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:38.514+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:38.520+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:38.520+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 34, in <module>
    start >> echo_hello >> end
NameError: name 'echo_hello' is not defined
[2024-04-08T07:54:38.521+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:38.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.031 seconds
[2024-04-08T07:54:48.140+0000] {processor.py:161} INFO - Started process (PID=38834) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:48.141+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:54:48.142+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:48.142+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:48.155+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:48.154+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/dog_api_pipeline.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dog_api_pipeline.py", line 35, in <module>
    start >> _get_dog_api >> end
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 104, in __rshift__
    self.set_downstream(other)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 262, in set_downstream
    self._set_relatives(task_or_task_list, upstream=False, edge_modifier=edge_modifier)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskmixin.py", line 214, in _set_relatives
    task_object.update_relative(self, not upstream, edge_modifier=edge_modifier)
AttributeError: 'function' object has no attribute 'update_relative'
[2024-04-08T07:54:48.155+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:48.190+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.053 seconds
[2024-04-08T07:54:50.955+0000] {processor.py:161} INFO - Started process (PID=38854) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:50.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:54:50.957+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:50.956+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:50.965+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:54:51.052+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:51.052+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:54:51.067+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:54:51.067+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:54:51.094+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.141 seconds
[2024-04-08T07:55:21.235+0000] {processor.py:161} INFO - Started process (PID=39117) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:21.236+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:55:21.238+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:21.238+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:21.247+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:21.271+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:21.271+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:55:21.299+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:21.299+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:55:21.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.092 seconds
[2024-04-08T07:55:51.508+0000] {processor.py:161} INFO - Started process (PID=39382) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:51.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:55:51.510+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:51.509+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:51.516+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:55:51.534+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:51.534+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:55:51.552+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:55:51.551+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:55:51.571+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.065 seconds
[2024-04-08T07:56:21.735+0000] {processor.py:161} INFO - Started process (PID=39644) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:21.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:56:21.738+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:21.737+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:21.746+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:21.770+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:21.769+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:56:21.807+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:21.806+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:56:21.855+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.123 seconds
[2024-04-08T07:56:39.248+0000] {processor.py:161} INFO - Started process (PID=39747) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:39.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:56:39.250+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:39.249+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:39.260+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:56:39.286+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:39.285+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:56:39.315+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:56:39.315+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:56:39.348+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.105 seconds
[2024-04-08T07:57:09.530+0000] {processor.py:161} INFO - Started process (PID=40009) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:09.530+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:57:09.531+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:09.531+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:09.540+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:09.564+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:09.563+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:57:09.589+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:09.589+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:57:09.624+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.097 seconds
[2024-04-08T07:57:40.400+0000] {processor.py:161} INFO - Started process (PID=40274) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:40.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:57:40.402+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:40.401+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:40.408+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:40.426+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:40.425+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:57:40.443+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:40.442+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:57:40.461+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.065 seconds
[2024-04-08T07:57:42.499+0000] {processor.py:161} INFO - Started process (PID=40279) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:42.500+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:57:42.501+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:42.501+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:42.517+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:57:42.562+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:42.562+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:57:42.614+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:57:42.614+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:57:42.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.237 seconds
[2024-04-08T07:58:02.533+0000] {processor.py:161} INFO - Started process (PID=40473) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:02.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:58:02.535+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:02.535+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:02.542+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:02.559+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:02.559+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:58:02.577+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:02.577+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:58:02.597+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.067 seconds
[2024-04-08T07:58:33.191+0000] {processor.py:161} INFO - Started process (PID=40738) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:33.192+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:58:33.193+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:33.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:33.203+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:58:33.235+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:33.234+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:58:33.253+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:58:33.253+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:58:33.271+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.084 seconds
[2024-04-08T07:59:03.446+0000] {processor.py:161} INFO - Started process (PID=41000) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:03.447+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:59:03.447+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:03.447+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:03.454+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:03.471+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:03.471+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:59:03.489+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:03.489+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:59:03.515+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.072 seconds
[2024-04-08T07:59:33.823+0000] {processor.py:161} INFO - Started process (PID=41262) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:33.824+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T07:59:33.824+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:33.824+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:33.830+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T07:59:33.847+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:33.847+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T07:59:33.864+0000] {logging_mixin.py:188} INFO - [2024-04-08T07:59:33.864+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T07:59:33.883+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.063 seconds
[2024-04-08T08:00:04.524+0000] {processor.py:161} INFO - Started process (PID=41518) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:04.526+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:00:04.527+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:04.526+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:04.536+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:04.559+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:04.558+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:00:04.585+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:04.585+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:00:04.608+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.087 seconds
[2024-04-08T08:00:34.715+0000] {processor.py:161} INFO - Started process (PID=41780) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:34.716+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:00:34.717+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:34.717+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:34.723+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:00:34.740+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:34.740+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:00:34.758+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:00:34.757+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:00:34.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.065 seconds
[2024-04-08T08:01:04.896+0000] {processor.py:161} INFO - Started process (PID=42041) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:04.898+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:01:04.899+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:04.898+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:04.909+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:04.937+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:04.937+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:01:04.961+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:04.961+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:01:04.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.091 seconds
[2024-04-08T08:01:35.280+0000] {processor.py:161} INFO - Started process (PID=42305) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:35.281+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:01:35.282+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:35.282+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:35.288+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:01:35.304+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:35.304+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:01:35.323+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:01:35.323+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:01:35.341+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.064 seconds
[2024-04-08T08:02:05.586+0000] {processor.py:161} INFO - Started process (PID=42550) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:05.587+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:02:05.588+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:05.588+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:05.596+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:05.620+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:05.620+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:02:05.646+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:05.646+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:02:05.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.088 seconds
[2024-04-08T08:02:11.216+0000] {processor.py:161} INFO - Started process (PID=42607) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:11.217+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:02:11.218+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:11.218+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:11.245+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:11.270+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:11.269+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:02:11.297+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:11.297+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:02:11.323+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.109 seconds
[2024-04-08T08:02:41.459+0000] {processor.py:161} INFO - Started process (PID=42872) to work on /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:41.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dog_api_pipeline.py for tasks to queue
[2024-04-08T08:02:41.461+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:41.461+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:41.471+0000] {processor.py:840} INFO - DAG(s) 'dog_api_pipeline' retrieved from /opt/airflow/dags/dog_api_pipeline.py
[2024-04-08T08:02:41.498+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:41.498+0000] {dag.py:3047} INFO - Sync 1 DAGs
[2024-04-08T08:02:41.525+0000] {logging_mixin.py:188} INFO - [2024-04-08T08:02:41.525+0000] {dag.py:3834} INFO - Setting next_dagrun for dog_api_pipeline to 2024-04-08 00:00:00+00:00, run_after=2024-04-09 00:00:00+00:00
[2024-04-08T08:02:41.552+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dog_api_pipeline.py took 0.096 seconds
