[2024-04-14T10:44:35.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-14T10:44:35.978+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.load_dataset_order manual__2024-04-14T10:15:09.605913+00:00 [queued]>
[2024-04-14T10:44:35.987+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.load_dataset_order manual__2024-04-14T10:15:09.605913+00:00 [queued]>
[2024-04-14T10:44:35.988+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-14T10:44:36.022+0000] {taskinstance.py:2327} INFO - Executing <Task(GCSToBigQueryOperator): load_dataset_order> on 2024-04-14 10:15:09.605913+00:00
[2024-04-14T10:44:36.035+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=196337) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-14T10:44:36.036+0000] {standard_task_runner.py:63} INFO - Started process 196357 to run task
[2024-04-14T10:44:36.034+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'load_dataset_order', 'manual__2024-04-14T10:15:09.605913+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmpbpgjh9la']
[2024-04-14T10:44:36.037+0000] {standard_task_runner.py:91} INFO - Job 107: Subtask load_dataset_order
[2024-04-14T10:44:36.083+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.load_dataset_order manual__2024-04-14T10:15:09.605913+00:00 [running]> on host 2ce858e27684
[2024-04-14T10:44:36.158+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl' AIRFLOW_CTX_TASK_ID='load_dataset_order' AIRFLOW_CTX_EXECUTION_DATE='2024-04-14T10:15:09.605913+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-14T10:15:09.605913+00:00'
[2024-04-14T10:44:36.160+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-04-14T10:44:36.166+0000] {connection.py:274} WARNING - Connection schemes (type: google_cloud_platform) shall not contain '_' according to RFC3986.
[2024-04-14T10:44:36.170+0000] {base.py:84} INFO - Using connection ID 'my_gcp_conn' for task execution.
[2024-04-14T10:44:36.171+0000] {gcs_to_bigquery.py:379} INFO - Using existing BigQuery table for storing data...
[2024-04-14T10:44:36.217+0000] {gcs_to_bigquery.py:383} INFO - Executing: {'load': {'autodetect': True, 'createDisposition': 'CREATE_IF_NEEDED', 'destinationTable': {'projectId': 'dataengineer-415510', 'datasetId': 'order', 'tableId': 'dataset_order'}, 'sourceFormat': 'CSV', 'sourceUris': ['gs://swu-ds-525-112233/order_bazilian.csv'], 'writeDisposition': 'WRITE_TRUNCATE', 'ignoreUnknownValues': False, 'skipLeadingRows': 1, 'fieldDelimiter': ',', 'quote': None, 'allowQuotedNewlines': 'true', 'encoding': 'UTF-8'}}
[2024-04-14T10:44:36.218+0000] {bigquery.py:1613} INFO - Inserting job ***_etl_load_dataset_order_2024_04_14T10_15_09_605913_00_00_4f1fe08e196cc8b8c9563f60ae380c12
[2024-04-14T10:45:27.555+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-04-14T10:45:27.566+0000] {taskinstance.py:1205} INFO - Marking task as SUCCESS. dag_id=etl, task_id=load_dataset_order, execution_date=20240414T101509, start_date=20240414T104435, end_date=20240414T104527
[2024-04-14T10:45:27.618+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-04-14T10:45:27.639+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-14T10:45:27.648+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
