[2024-04-22T06:33:31.307+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-04-22T06:33:31.557+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl.upload_file_payments scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-22T06:33:31.768+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl.upload_file_payments scheduled__2024-04-19T00:00:00+00:00 [queued]>
[2024-04-22T06:33:31.822+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2024-04-22T06:33:32.116+0000] {taskinstance.py:2327} INFO - Executing <Task(LocalFilesystemToGCSOperator): upload_file_payments> on 2024-04-19 00:00:00+00:00
[2024-04-22T06:33:32.523+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl', 'upload_file_payments', 'scheduled__2024-04-19T00:00:00+00:00', '--job-id', '194', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmptyhda4ww']
[2024-04-22T06:33:32.558+0000] {standard_task_runner.py:91} INFO - Job 194: Subtask upload_file_payments
[2024-04-22T06:33:32.552+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2072) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-04-22T06:33:32.595+0000] {standard_task_runner.py:63} INFO - Started process 2267 to run task
[2024-04-22T06:33:33.097+0000] {task_command.py:426} INFO - Running <TaskInstance: etl.upload_file_payments scheduled__2024-04-19T00:00:00+00:00 [running]> on host af114bcfa67a
[2024-04-22T06:34:00.230+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 194 for task upload_file_payments ((psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8); 2267)
[2024-04-22T06:34:00.801+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-04-22T06:34:10.338+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-04-22T06:34:10.381+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
